/*
 * This source file was generated by the Gradle 'init' task
 */
package com.vranec;

public class VacationApplication {

    static void main() {
        new VacationApplication().exportToCsv();
    }

    public void exportToCsv() {
        var configuration = new Configuration();
        var fischerDownloader = new FischerDownloader(configuration);
        var csvExporter = new CsvExporter();
        csvExporter.export(fischerDownloader);
    }
}
