/*
 * This source file was generated by the Gradle 'init' task
 */
package com.vranec;

public class VacationApplication {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new VacationApplication().getGreeting());
    }
}
