/*
 * This source file was generated by the Gradle 'init' task
 */
package com.vranec;

public class VacationApplication {

    public static void main(String[] args) {
        new VacationApplication().exportToCsv();
    }

    public void exportToCsv() {
        var configuration = new Configuration();
        var fischerDownloader = new FischerDownloader(configuration.getListings().getFirst());
        var csvExporter = new CsvExporter();
        csvExporter.export(fischerDownloader);
    }
}
