/*
 * This source file was generated by the Gradle 'init' task
 */
package com.vranec;

import com.github.tomakehurst.wiremock.junit5.WireMockTest;
import org.junit.jupiter.api.Test;

import java.nio.file.Paths;

import static com.github.tomakehurst.wiremock.client.WireMock.aResponse;
import static com.github.tomakehurst.wiremock.client.WireMock.anyUrl;
import static com.github.tomakehurst.wiremock.client.WireMock.get;
import static com.github.tomakehurst.wiremock.client.WireMock.getRequestedFor;
import static com.github.tomakehurst.wiremock.client.WireMock.stubFor;
import static com.github.tomakehurst.wiremock.client.WireMock.urlMatching;
import static com.github.tomakehurst.wiremock.client.WireMock.verify;
import static java.nio.file.Files.readString;
import static java.util.Objects.requireNonNull;
import static org.assertj.core.api.Assertions.assertThat;

@WireMockTest(httpPort = 18080)
class VacationApplicationTest {

    @Test
    void exportToCsv_exportsListingsToCsv() throws Exception {
        stubFor(get(anyUrl()).willReturn(aResponse()
                .withHeader("Content-Type", "application/json")
                .withBodyFile("fischer.json")));
        stubFor(get(urlMatching(".*&dd=2025-07-19.*")).willReturn(aResponse()
                .withHeader("Content-Type", "application/json")
                .withBodyFile("fischer-with-bello-possible.json")));

        new VacationApplication().exportToCsv();

        var content = readString(Paths.get("results.csv"));
        var path = Paths.get(requireNonNull(getClass().getResource("/expected-results.csv")).toURI());
        var expectedContent = readString(path);
        assertThat(content).isEqualTo(expectedContent);
        verify(90, getRequestedFor(anyUrl()));
    }
}
